language: java

dist: trusty

jdk:
  - openjdk11

addons:
  chrome: stable
  firefox: latest
  apt:
    packages:
      - chromium-chromedriver

cache:
  directories:
    - "${HOME}/.m2/"

install: true

before_script: ci/before_script.sh

script: ci/script.sh
