language: java

dist: trusty

jdk:
  - openjdk11

addons:
  chrome: stable
  firefox: "69.0.1"
  apt:
    packages:
      # ChromeDriver
      - chromium-chromedriver
      # Japanese
      - language-pack-ja
      - japan*
      # Chinese
      - language-pack-zh*
      - chinese*
      # Korean
      - language-pack-ko
      - korean*
      # Fonts
      - fonts-arphic-ukai
      - fonts-arphic-uming
      - fonts-ipafont-mincho
      - fonts-ipafont-gothic
      - fonts-unfonts-core

cache:
  directories:
    - "${HOME}/.m2/"

install: true

before_script: ci/before_script.sh

script: ci/script.sh
