(self.AMP=self.AMP||[]).push({n:"amp-install-serviceworker",v:"1910071803120",f:(function(AMP,_){
var l="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},m;if("function"==typeof Object.setPrototypeOf)m=Object.setPrototypeOf;else{var n;a:{var p={a:!0},q={};try{q.__proto__=p;n=q.a;break a}catch(a){}n=!1}m=n?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var r=m;function t(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var v=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function w(a){var b=Object.create(null);if(!a)return b;for(var c;c=v.exec(a);){var d=t(c[1],c[1]),e=c[2]?t(c[2],c[2]):"";b[d]=e}return b};var x="";
function y(){var a,b=a||self;if(b.__AMP_MODE)var c=b.__AMP_MODE;else{c=b;var d=self.AMP_CONFIG||{},e=!!d.test||!1,h=c.__karma__&&c.__karma__.config.amp.testOnIe,f=w(c.location.originalHash||c.location.hash);d=d.spt;var g=w(c.location.search);x||(x=c.AMP_CONFIG&&c.AMP_CONFIG.v?c.AMP_CONFIG.v:"011910071803120");c={localDev:!1,development:!!(0<=["1","actions","amp","amp4ads","amp4email"].indexOf(f.development)||c.AMP_DEV_MODE),examiner:"2"==f.development,filter:f.filter,geoOverride:f["amp-geo"],userLocationOverride:f["amp-user-location"],
minified:!0,lite:void 0!=g.amp_lite,test:e,testIe:h,log:f.log,version:"1910071803120",rtvVersion:x,singlePassType:d};c=b.__AMP_MODE=c}return c};var z=self.AMP_CONFIG||{},A={thirdParty:z.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:z.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof z.thirdPartyFrameRegex?new RegExp(z.thirdPartyFrameRegex):z.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:z.cdnUrl||"https://cdn.ampproject.org",cdnProxyRegex:("string"==typeof z.cdnProxyRegex?new RegExp(z.cdnProxyRegex):z.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,
errorReporting:z.errorReportingUrl||"https://amp-error-reporting.appspot.com/r",localDev:z.localDev||!1,trustedViewerHosts:[/(^|\.)google\.(com?|[a-z]{2}|com?\.[a-z]{2}|cat)$/,/(^|\.)gmail\.dev$/]};self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var B=self.__AMP_LOG;function C(){if(!B.user)throw Error("failed to call initLogConstructor");return B.user}function D(a,b,c,d,e){C().assert(a,b,c,d,e,void 0,void 0,void 0,void 0,void 0,void 0)};function E(a){return a||{}};E({c:!0,v:!0,a:!0,ad:!0,action:!0});function F(a){var b=a.indexOf("#");return-1==b?a:a.substring(0,b)};function G(a){var b="";try{"localStorage"in a&&(b=a.localStorage.getItem("amp-experiment-toggles"))}catch(e){if(B.dev)a=B.dev;else throw Error("failed to call initLogConstructor");a.warn("EXPERIMENTS","Failed to retrieve experiments from localStorage.")}var c=b?b.split(/\s*,\s*/g):[];a=Object.create(null);for(var d=0;d<c.length;d++)0!=c[d].length&&("-"==c[d][0]?a[c[d].substr(1)]=!1:a[c[d]]=!0);return a};function H(a){var b=a.ownerDocument.defaultView,c=b.__AMP_TOP||(b.__AMP_TOP=b),d=b!=c;var e=c;if(e.__AMP__EXPERIMENT_TOGGLES)var h=e.__AMP__EXPERIMENT_TOGGLES;else{e.__AMP__EXPERIMENT_TOGGLES=Object.create(null);h=e.__AMP__EXPERIMENT_TOGGLES;if(e.AMP_CONFIG)for(var f in e.AMP_CONFIG){var g=e.AMP_CONFIG[f];"number"===typeof g&&0<=g&&1>=g&&(h[f]=Math.random()<g)}if(e.AMP_CONFIG&&Array.isArray(e.AMP_CONFIG["allow-doc-opt-in"])&&0<e.AMP_CONFIG["allow-doc-opt-in"].length&&(f=e.AMP_CONFIG["allow-doc-opt-in"],
g=e.document.head.querySelector('meta[name="amp-experiments-opt-in"]'))){g=g.getAttribute("content").split(",");for(var k=0;k<g.length;k++)-1!=f.indexOf(g[k])&&(h[g[k]]=!0)}Object.assign(h,G(e));if(e.AMP_CONFIG&&Array.isArray(e.AMP_CONFIG["allow-url-opt-in"])&&0<e.AMP_CONFIG["allow-url-opt-in"].length)for(f=e.AMP_CONFIG["allow-url-opt-in"],e=w(e.location.originalHash||e.location.hash),g=0;g<f.length;g++)k=e["e-"+f[g]],"1"==k&&(h[f[g]]=!0),"0"==k&&(h[f[g]]=!1)}var u=!!h["ampdoc-fie"];d&&!u?a=I(b,"url")?
J(b,"url"):null:(a=K(a),a=L(a),a=I(a,"url")?J(a,"url"):null);return a}function M(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return J(a,b)}function N(a){var b=K(a);b=L(b);return J(b,"documentInfo")}function K(a){return a.nodeType?M((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function L(a){a=K(a);return a.isSingleDoc()?a.win:a}
function J(a,b){I(a,b);var c=a.__AMP_SERVICES;c||(c=a.__AMP_SERVICES={});var d=c;a=d[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function I(a,b){a=a.__AMP_SERVICES&&a.__AMP_SERVICES[b];return!(!a||!a.ctor&&!a.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function O(a,b){for(var c;a&&a!==c;a=a.parentElement)if(b(a))return a;return null}function P(a){return a.closest?a.closest("A"):O(a,function(a){var b=a.matches||a.webkitMatchesSelector||a.mozMatchesSelector||a.msMatchesSelector||a.oMatchesSelector;return b?b.call(a,"A"):!1})};var Q;function R(a,b){var c=void 0,d=a,e=b;var h=function(a){try{return e(a)}catch(u){throw self.__AMP_REPORT_ERROR(u),u;}};var f=aa(),g=!1;c&&(g=c.capture);d.addEventListener("click",h,f?c:g)}function aa(){if(void 0!==Q)return Q;Q=!1;try{var a={get capture(){Q=!0}};self.addEventListener("test-options",null,a);self.removeEventListener("test-options",null,a)}catch(b){}return Q};function S(a){var b=!1;void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","")};function T(a){a=AMP.BaseElement.call(this,a)||this;a.h=null;a.B=null;a.j=M(a.win,"platform").isSafari();return a}var U=AMP.BaseElement;T.prototype=l(U.prototype);T.prototype.constructor=T;if(r)r(T,U);else for(var V in U)if("prototype"!=V)if(Object.defineProperties){var W=Object.getOwnPropertyDescriptor(U,V);W&&Object.defineProperty(T,V,W)}else T[V]=U[V];T.C=U.prototype;
T.prototype.buildCallback=function(){var a=this,b=this.win;if("serviceWorker"in b.navigator){var c=H(this.element),d=this.element.getAttribute("src");c.assertHttpsUrl(d,this.element);if(!c.isProxyOrigin(d)&&!c.isProxyOrigin(b.location.href)||this.j)c.parse(b.location.href).origin==c.parse(d).origin?X(this).then(function(){return ba(a.win,d,a.element)}):this.user().error("amp-install-serviceworker","Did not install ServiceWorker because it does not match the current origin: "+d);else{var e=this.element.getAttribute("data-iframe-src");
if(e){c.assertHttpsUrl(e,this.element);var h=c.parse(e).origin,f=N(this.element).get(),g=c.parse(f.sourceUrl),k=c.parse(f.canonicalUrl);D(h==g.origin||h==k.origin,"data-iframe-src (%s) should be a URL on the same origin as the source (%s) or canonical URL (%s) of the AMP-document.",h,g.origin,k.origin);this.h=e;X(this).then(function(){return ca(a)})}}(c.isProxyOrigin(d)||c.isProxyOrigin(b.location.href))&&this.j&&this.user().error("amp-install-serviceworker","Did not install ServiceWorker because of safari double keyring caching as it will not have any effect")}else da(this)};
function X(a){return Promise.all([a.loadPromise(a.win),a.getAmpDoc().whenFirstVisible()])}function ca(a){return a.mutateElement(function(){S(a.element);var b=a.win.document.createElement("iframe");b.setAttribute("sandbox","allow-same-origin allow-scripts");b.src=a.h;a.element.appendChild(b)})}
function da(a){if(a.getAmpDoc().isSingleDoc()){var b=a.getAmpDoc(),c=a.win,d=H(a.element),e=d.parse(c.location.href),h=a.element.getAttribute("data-no-service-worker-fallback-url-match"),f=a.element.getAttribute("data-no-service-worker-fallback-shell-url");if(h||f){D(h&&f,'Both, "%s" and "%s" must be specified for url-rewrite',"data-no-service-worker-fallback-url-match","data-no-service-worker-fallback-shell-url");f=F(f);try{var g=new RegExp(h)}catch(k){throw C().createError('Invalid "data-no-service-worker-fallback-url-match" expression',
k);}D(d.getSourceOrigin(e)==d.parse(f).origin,'Shell source origin "%s" must be the same as source origin "%s"',f,e.href);a.B=new Y(b,g,f,a.element);d.isSecure(f)&&ea(a,f)}}}function ea(a,b){X(a).then(function(){a.mutateElement(function(){return fa(a,b)})})}
function fa(a,b){var c=a.win.document.createElement("iframe");c.id="i-amphtml-shell-preload";c.setAttribute("src",b+"#preload");S(c);c.setAttribute("sandbox","allow-scripts allow-same-origin");var d=a.loadPromise(c);d.then(function(){c.parentElement&&c.parentElement.removeChild(c)});a.element.appendChild(c)}function Y(a,b,c,d){this.win=a.win;this.A=b;this.w=c;this.m=H(d);this.l=this.m.parse(c);a=a.getRootNode();b=this.o.bind(this);R(a,b)}
Y.prototype.o=function(a){if(!a.defaultPrevented&&(a=P(a.target))&&a.href){var b=this.m.parse(a.href);if(b.origin==this.l.origin&&b.pathname!=this.l.pathname&&this.A.test(b.href)&&!a.getAttribute("i-amphtml-orig-href")){var c=this.win;F(b.href)!=F(c.location.href)&&(a.setAttribute("i-amphtml-orig-href",a.href),a.href=this.w+"#href="+encodeURIComponent(""+b.pathname+b.search+b.hash))}}};
function ba(a,b,c){var d={};c.hasAttribute("data-scope")&&(d.scope=c.getAttribute("data-scope"));return a.navigator.serviceWorker.register(b,d).then(function(b){y().development&&C().info("amp-install-serviceworker","ServiceWorker registration successful with scope: ",b.scope);var e=b.installing;e?e.addEventListener("statechange",function(e){"activated"===e.target.state&&Z(b,a,c)}):b.active&&Z(b,a,c);return b},function(a){C().error("amp-install-serviceworker","ServiceWorker registration failed:",a)})}
function Z(a,b,c){ha(b,a);c.hasAttribute("data-prefetch")&&ia(a,b)}function ha(a,b){if("performance"in a){var c=a.performance.getEntriesByType("resource").filter(function(a){var b;if(b="script"===a.initiatorType)a=a.name,b=A.cdn,b=b.length>a.length?!1:0==a.lastIndexOf(b,0);return b}).map(function(a){return a.name}),d=b.active;d.postMessage&&d.postMessage(JSON.stringify(E({type:"AMP__FIRST-VISIT-CACHING",payload:c})))}}
function ia(a,b){var c=b.document,d=[].map.call(c.querySelectorAll("a[data-rel=prefetch]"),function(a){return a.href});ja(c)?d.forEach(function(a){var b=c.createElement("link");b.setAttribute("rel","prefetch");b.setAttribute("href",a);c.head.appendChild(b)}):(a=a.active,a.postMessage&&a.postMessage(JSON.stringify(E({type:"AMP__LINK-PREFETCH",payload:d}))))}function ja(a){var b=a.createElement("link");return b.relList&&b.relList.supports?b.relList.supports("prefetch"):!1}
(function(a){a.registerElement("amp-install-serviceworker",T)})(self.AMP);
})});

//# sourceMappingURL=amp-install-serviceworker-0.1.js.map
